version: "3.9"
networks:
  ta1-service:
    driver: bridge
    name: ta1-service
  data-api:
    external: true
services:
  extraction-api:
    container_name: api-ta1-service
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - api.env
    networks:
      - ta1-service
      - data-api
    depends_on:
      - redis
    volumes:
      - $PWD/api:/service/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis-ta1-service
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ta1-service
  rqworker:
    container_name: worker-ta1-service
    build:
      context: ./
      dockerfile: workers/Dockerfile
    env_file:
      - api.env
    depends_on:
      - redis
    networks:
      - ta1-service
      - data-api
  mit-tr:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: mit-tr
    networks:
      - ta1-service
  skema-tr:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-tr
    networks:
      - ta1-service
  skema-py:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-py
    networks:
      - ta1-service
  skema-unified:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-unified
  skema-rs:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-rs
    networks:
      - ta1-service
  graphdb:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: graphdb
    networks:
      - ta1-service
  eq2mml:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: eq2mml
    networks:
      - ta1-service
  mathjax:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: mathjax
    networks:
      - ta1-service

volumes:
  mg_lib:
  mg_log:
  mg_etc:
