---
version: "3.9"
networks:
  knowledge-middleware:
    driver: bridge
    name: knowledge-middleware
  data-api:
    external: true
services:
  api:
    container_name: api-knowledge-middleware
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - .env
    networks:
      - knowledge-middleware
      - data-api
    depends_on:
      - redis
    volumes:
      - $PWD/api:/service/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis-knowledge-middleware
    image: redis
    ports:
      - "6379:6379"
    networks:
      - knowledge-middleware
  rqworker:
    container_name: worker-knowledge-middleware
    build:
      context: ./
      dockerfile: worker/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - knowledge-middleware
      - data-api

volumes:
  mg_lib:
  mg_log:
  mg_etc:
