version: "3.9"
networks:
  ta1-service:
    driver: bridge
    name: ta1-service
services:
  api:
    container_name: api-ta1-service
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - api.env
    networks:
      - ta1-service
    depends_on:
      - redis
    volumes:
      - $PWD/api:/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis-ta1-service
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ta1-service
  rqworker:
    container_name: worker-ta1-service
    build:
      context: ./
      dockerfile: workers/Dockerfile
    env_file:
      - api.env
    depends_on:
      - redis
    networks:
      - ta1-service