---
version: "3.9"
networks:
  knowledge-middleware:
    driver: bridge
    name: knowledge-middleware
  data-api:
    external: true
services:
  extraction-api:
    container_name: api-knowledge-middleware
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - .env
    networks:
      - knowledge-middleware
      - data-api
    depends_on:
      - redis
    volumes:
      - $PWD/api:/service/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis-knowledge-middleware
    image: redis
    ports:
      - "6379:6379"
    networks:
      - knowledge-middleware
  rqworker:
    container_name: worker-knowledge-middleware
    build:
      context: ./
      dockerfile: worker/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - knowledge-middleware
      - data-api
  mit-tr:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: mit-tr
    networks:
      - knowledge-middleware
  skema-tr:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-tr
    networks:
      - knowledge-middleware
  skema-py:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-py
    networks:
      - knowledge-middleware
  skema-unified:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-unified
    networks:
      - knowledge-middleware
  skema-rs:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: skema-rs
    networks:
      - knowledge-middleware
  graphdb:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: graphdb
    networks:
      - knowledge-middleware
  eq2mml:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: eq2mml
    networks:
      - knowledge-middleware
  mathjax:
    extends:
      file: ./askem-ta1-dockervm/end-to-end-rest/docker-compose.yml
      service: mathjax
    networks:
      - knowledge-middleware

volumes:
  mg_lib:
  mg_log:
  mg_etc:
