[tool.poetry]
name = "ta1-service"
version = "0.1.0"
description = ""
authors = ["Powell Fendley"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
redis = "^4.6.0"
rq = "^1.15.1"
pydantic = "^2.0.2"
idna = "^3.4"
python-multipart = "^0.0.6"
pandas = "^2.0.3"

uvicorn = { version = "^0.22.0", optional = true }
fastapi = { version = "^0.100.0", optional = true }
pypdf = { version = "^3.12.0", optional = true }
pytest = "^7.4.0"
httpx = "0.23.3"
requests = "^2.31.0"
fakeredis = "^2.17.0"
pytest-cov = "^4.1.0"
pact-python = "^2.0.1"
jsonschema = "^4.19.0"


[tool.poetry.extras]
api = ["uvicorn", "fastapi", "pypdf", "pandas"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"