[tool.poetry]
name = "extraction-service"
version = "0.1.0"
description = ""
authors = ["Powell Fendley"]
readme = "README.md"
packages = [{include = "extraction_service"}]



[tool.poetry.dependencies]
python = "^3.9"
redis = "^4.6.0"
rq = "^1.15.1"
pydantic = "^2.0.2"
idna = "^3.4"
python-multipart = "^0.0.6"
pandas = "^2.0.3"

uvicorn = { version = "^0.22.0", optional = true }
fastapi = { version = "^0.100.0", optional = true }
pypdf = { version = "^3.12.0", optional = true }


[tool.poetry.extras]
api = ["uvicorn", "fastapi", "pypdf", "pandas"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
